services:
  allinone:
    image: youshandefeiyang/allinone
    container_name: allinone
    privileged: true
    restart: always
    ports:
      - "35455:35455"
    network_mode: bridge
    command: -tv=true -aesKey=jmxk5hjhwimpan91fubnczgkxtyw7rb3 -userid=7556736462 -token=ee253c707536cec9655e69ac666f3c17456c08e88ddbf9dbb633f725f88c3de9fbffe91d4a1203e68e8af9f8771edb94bf78d2f0554fafec53c0fb59db8076dcd51caf6e41fe2f
